version: '3.8'

services:
  telegram-n8n-bridge:
    image: telegram-n8n-bridge:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-n8n-bridge
    restart: unless-stopped
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - ALLOW_CHATS=${ALLOW_CHATS:-*}
      - FORWARD_MEDIA=${FORWARD_MEDIA:-true}
    volumes:
      - telegram_session:/app/session
    networks:
      - telegram-bridge-network

volumes:
  telegram_session:
    driver: local

networks:
  telegram-bridge-network:
    driver: bridge
